# SST Transition Dates


```{r, echo = FALSE,message = FALSE,warning = FALSE }
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = 'center') #allows for inserting R code into captions
library(tidyverse)
dat<- read.csv(here::here("EPU_transition_dates.csv")) %>% 
  filter(!EPU == "NA")

dat<- dat %>% pivot_longer(cols = sprtrans:sumlen30, names_to = "Var", values_to = "Value")
```

#### ltm compare

```{r}
regdata<- read.csv(file.path(here::here("data-raw/TS_SHP_adv rep MAB GOM GBK NES SCSPoly.csv"))) %>%
  dplyr::filter(Location %in% c("GBK", "GOM", "MAB"))

ltm <- regdata %>% 
  dplyr::filter(Y %in% 1982:2012) %>% 
  dplyr::group_by(Date, Location) %>% 
  dplyr::summarise(ltm = mean(Mean)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(hline = mean(ltm))

y2021<- regdata %>% 
  dplyr::filter(Y == 2021)
regdata %>% 
  ggplot2::ggplot(aes(x = Date, y = Mean, color = Y))+
  ggplot2::geom_line()+
  ggplot2::geom_line(data = ltm, aes(x = Date, y = ltm), color = "black") +
  geom_line(data = ltm, aes(x = Date, y = hline), color = "black", linetype = "dashed" )+
  ggplot2::geom_line(data = y2021, aes(x = Date, y = Mean), color = "red" ) +
  facet_wrap(.~Location)
  
  
```

## Spring and Fall transition dates - mean to 30%

```{r}
dat %>% filter(Var %in% c("sprtrans", "falltrans",
                          "sprtrans10", "falltrans10",
                          "sprtrans20", "falltrans20",
                          "sprtrans30", "falltrans30", "maxday")) %>% 
  ggplot2::ggplot()+
  geom_line(aes(x = Time, y = Value, color = Var))+
  facet_wrap(~EPU)
```

## Length of Summer mean to 30%

```{r}
gls<- dat %>% filter(Var == "sumlen", 
                     !Value == "NA") %>% 
  mutate(Time = as.numeric(Time), 
         Value = as.numeric(Value))

dat %>% filter(Var %in% c("sumlen", "sumlen10", 
                          "sumlen20", "sumlen30")) %>%
  mutate(Time = as.numeric(Time), 
         Value = as.numeric(Value)) %>% 
  ggplot2::ggplot(aes(x = Time, y = Value, color = Var))+
  geom_line()+
  facet_wrap(~EPU)


```


